In [1]:
import pandas as pd
import numpy as np

In [17]:
data =  pd.read_csv('play_tennis.csv')

In [18]:
data.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [7]:
# problem 1 

# outlook - sunny,temp = hot,humidity = high,wind  =weak
# play or no play?

In [8]:
#solution

#p(yes/sunny,hot,high,weak) = P(sunny/yes) * P(hot/yes) *P(high/yes)* p(weak/yes) *p(yes)

#p(No/sunny,hot,high,weak) = P(sunny/No) * P(hot/no) *P(high/No)* p(weak/No) *p(No)

# compare and decide using the maximum a posteriori Rule

In [9]:
# problem 2 
# outlook - overcast,temp = cold,humidity = low,wind = weak
#play or no play?

In [10]:
#solution

#p(Yes/overcast,cold,low,weak) = P(overcast/Yes)* P(cold/yes)* p(low/yes)*p(weak/Yes) * p(yes)

#P(Yes/overcast,cold,loww,weak) =  P(overcast/YNo)* P(cold/no)* p(low/No)*p(weak/No) * p(No)

# compare and decide using the maximum a posteriori Rule

In [11]:
# trainig

# lookupTable(dictionary)

# testing

In [12]:
#P(yes)
#p(no)

In [19]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [20]:
py = 9/14
pn = 5/14

In [21]:
# outlook 
pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [30]:
Pon = 0
prn = 2/4
Psn = 3/5

poy = 4/9
pry = 3/9
psy = 2/9

In [23]:
# temp = 
pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [24]:
pcoolNo = 1/5
photno = 2/5
pmildno = 2/5

pcoolyes = 3/9
photyes = 2/9
pmildyes = 4/9

In [25]:
# humidity
pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [26]:
PhighNo = 4/5
pnormalno = 1/5

phighyes = 3/9
pnormalyes = 6/9

In [27]:
# wind 
pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [28]:
Pstrongno = 3/5
pweakno = 2/5

pstrongyes = 3/9
pweakyes = 6/9

In [31]:
 #outlook - sunny,temp = hot,humidity = high,wind  =weak

pyes = py*psy*photyes*phighyes*pweakyes
print(pyes)

0.007054673721340388

In [34]:
Pno =  pn*Psn*photno*PhighNo*pweakno
print(Pno)

0.02742857142857143

In [35]:
# no play